version: "3.9"

services: 
  frontend:
    image: nginx
    ports: 
      - 80:80
    volumes: 
      - ./:/home/box/web/
      - ./etc/nginx-d.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - webapp

  backend:
    build: 
      context: ./
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/home/box/web/
    ports: 
      - 8080:8080
      - 8000:8000
    networks: 
      - webapp
    # command: tail -F anything

  database:
    image: mysql:5.5.54
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
    networks: 
      - webapp

networks:
  webapp:
