version: "3.9"

services: 
  frontend:
    image: nginx
    ports: 
      - 80:80
    volumes: 
      - ./:/home/box/web/
      - ./etc/nginx-d.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - webapp
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build: 
      context: ./
      dockerfile: backend.Dockerfile
    volumes:
      - ./:/home/box/web/
    ports: 
      - 8080:8080
      - 8000:8000
    networks: 
      - webapp
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://0.0.0.0:8000/ || exit 1
      interval: 30s
      start_period: 20s


  database:
    image: mysql:5.5.54
    restart: always
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - 3306:3306
    networks: 
      - webapp
    healthcheck:
      test: mysqladmin ping -h localhost
      timeout: 5s
      interval: 5s

networks:
  webapp:
